services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=conduit'
      - 'POSTGRES_PASSWORD=conduit'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
  zipkin:
    container_name: zipkin
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411:9411'