spring:
  application:
    name: conduit
  datasource:
    url: localhost:5432/conduit
    username: user
    password: conduit
  docker:
    compose:
      lifecycle-management: start_only
  sql:
    init:
      mode: always

logging:
  level:
    root: info
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 1
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
