spring:
  application:
    name: conduit
  datasource:
    url: jdbc:postgresql://localhost:5432/conduit
    username: user
    password: conduit
  docker:
    compose:
      lifecycle-management: start_only
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: false


logging:
  level:
    root: info
    org.springframework:
      jdbc: debug
      security: debug
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 1
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
